name: Daily Supabase CSV Export

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  TABLES_TO_EXPORT: 'pois,raceTracks,gangs,enteringPw,pw'

jobs:
  export-and-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create exports directory
        run: mkdir -p exports

      - name: Export Supabase tables to CSV
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node scripts/export-csv.js

      - name: Send email via Gmail
        env:
          GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: node scripts/email-utils.js

      - name: Clean up exported files
        run: rm -rf exports/
        if: always()
